@startuml
class GestorDeJuego{
-rondas:int
-jugadores:list
-tablero:Tablero
-ladron:Ladron
+inicializarPartida()
+tirarDado()
+cosecharRecursos()
+verificarLadron)
+incrementarRonda()
+verificarGanador()
}

class Tablero{
-puertos:list
-terrenos:list
-validarDistancia(piezaNueva)
+agregarPieza(pieza)
}

Interface Puerto{
+intercambiar()
}

class PuertoGenerico{
+intercambiar(jugador,oferta,recurso)
}

class PuertoEspecifico{
-recursoAceptado:String
+intercambiar(jugador,recursoSolicitado)
}

class Ladron{
-ubicacion
+robar()
+enDesierto():boolean
}

class Jugador{
-nombre:String
-caminos:list
-gestorDePiezas: GestorDePiezas
-recursos:list
-cartas:list
+Jugador(gestorDePiezas):void
+solicitarIntercambio(oferta:list, recursoSolicitado:String)
+incrementarRecurso(recurso,incremento)
+calcularPuntajeTotal():int
}

class GestorDePiezas{
-tablero:Tablero
-cantCaminos
-cantCiudades
-cantAsentamientos
-caminos:list
-asentamientos:list
-ciudades: list
+GestorDePiezas(tableroEnJuego):void
+caminoMasLargo(): list
+puntajeDePiezas():int
+eliminarPieza(pieza):void
+incorporarPieza(pieza,ubicacion):void
}

Abstract class Pieza{
-ubicacion:list
-jugadorPerteneciente:JUgador
+enPuerto:boolean
+validarColocacion(ubicacion)
+colocar(ubicacion)
+costoConstruccion()
}

class Camino{
+Validarcolocacion(ubicacion)
+costoConstruccion()
}

class Ciudad{
+validarColocacion(ubicacion)
+costoConstruccion()
}

class Asentamiento{
+validarColocacion(ubicacion)
+costoConstruccion()
}

class Recurso{
-tipo:string
-cantidad:int
+incrementar(cantidad):void
+decrementar(cantidad): void
+sosTipo(unTipo): bool
}

Abstract class Terreno {
-numero:int
-tieneLadron:boolean
-piezasAdyacentes:list
+repartirRecurso()
+bloquearConLadron()
+liberarDeLadron()
+agregarPiezaAdyacente()
+eliminarPiezaAdyacente()
}

class Bosque{
+repartirRecurso()
}

class Colina{
+repartirRecurso()
}

class Pastizal{
+repartirRecurso()
}

class Campo{
+repartirRecurso()
}

class Montaña{
+repartirRecurso()
}


Abstract class Carta{
-cantidad
+usar()
+obtenerpuntaje():int
}

class Caballero{
+usar()
+obtenerpuntaje():int

}

class PuntosDeVictoria{
+usar()
+obtenerpuntaje():int

}

class Progreso{
+usar()
+obtenerpuntaje():int

}

Carta <|-- Caballero
Carta <|-- PuntosDeVictoria
Carta <|-- Progreso
GestorDeJuego o-- Tablero
GestorDeJuego o-- Jugador
GestorDeJuego --> Ladron
Puerto <|.. PuertoEspecifico
Puerto <|.. PuertoGenerico
Tablero o-- Puerto
Tablero o-- Terreno
Terreno <|-- Bosque
Terreno <|-- Pastizal
Terreno <|-- Campo
Terreno <|-- Montaña
Terreno <|-- Colina
Terreno ..> Recurso
Jugador --> Recurso
Jugador --> GestorDePiezas
Jugador --> Carta
GestorDePiezas --> Tablero
GestorDePiezas o-- Pieza
Pieza <|-- Camino
Pieza <|-- Asentamiento
Pieza <|-- Ciudad
@enduml
